const createReminderEmailHtml = ({
  title,
  description,
  imageUrl,
  adminName,
  adminEmail,
  companyName,
  sendDate,
}) => `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reminder</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        background-color: #f4f6fb;
        color: #22344d;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      }
      .email-shell {
        width: 100%;
        max-width: 680px;
        margin: 0 auto;
        background: #ffffff;
        border-radius: 18px;
        overflow: hidden;
        box-shadow: 0 20px 60px rgba(34, 52, 77, 0.08);
      }
      .email-header {
        padding: 32px 30px 22px;
        background: linear-gradient(135deg, #4f6cff 0%, #0f3ee2 100%);
        color: #ffffff;
      }
      .email-header h1 {
        margin: 0;
        font-size: 26px;
        line-height: 32px;
      }
      .email-content {
        padding: 28px 30px 32px;
      }
      .email-meat {
        font-size: 16px;
        line-height: 1.8;
        color: #334155;
      }
      .email-image {
        width: 100%;
        border-radius: 16px;
        margin: 22px 0;
        object-fit: cover;
      }
      .email-footer {
        padding: 24px 30px 32px;
        background: #f8fafc;
        color: #64748b;
        font-size: 14px;
        line-height: 1.6;
      }
      .email-footer strong {
        color: #0f3ee2;
      }
      .meta-row {
        margin-top: 18px;
        padding: 18px 20px;
        background: #f1f5f9;
        border-radius: 14px;
      }
      .meta-row p {
        margin: 0 0 8px;
      }
      .meta-row p:last-child {
        margin-bottom: 0;
      }
    </style>
  </head>
  <body>
    <div class="email-shell">
      <div class="email-header">
        <h1>Reminder from ${companyName || "Your team"}</h1>
      </div>
      <div class="email-content">
        <p class="email-meat">Hello ${companyName || "team"},</p>
        <p class="email-meat">You have a new reminder message:</p>

        <div class="meta-row">
          <p><strong>${title}</strong></p>
          <p>${description.replace(/\n/g, '<br/>')}</p>
        </div>

        ${imageUrl ? `<img src="${imageUrl}" alt="Reminder image" class="email-image" />` : ""}

        <div class="meta-row">
          <p><strong>Sent by:</strong> ${adminName}${adminEmail ? ` (${adminEmail})` : ""}</p>
          <p><strong>Sent on:</strong> ${sendDate.toLocaleString("en-IN", {
            year: "numeric",
            month: "long",
            day: "numeric",
            hour: "2-digit",
            minute: "2-digit",
          })}</p>
        </div>

        <p class="email-meat">If you have questions, reply to this email and your admin will follow up.</p>
      </div>
      <div class="email-footer">
        <p>This email was generated by MyMunc SaaS reminder service.</p>
        <p><strong>${companyName || "Company"}</strong> • Sent by ${adminName}</p>
      </div>
    </div>
  </body>
  </html>
`;

module.exports = { createReminderEmailHtml };